# Generated by Django 2.0 on 2017-12-26 05:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='F', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, unique=True)),
                ('low_age', models.IntegerField()),
                ('high_age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('place', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('length', models.IntegerField()),
                ('reg_athletes', models.ManyToManyField(to='llegada.Athlete')),
            ],
        ),
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_record', models.DurationField(default=datetime.timedelta(0))),
                ('result_athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llegada.Athlete')),
                ('result_race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llegada.Race')),
            ],
        ),
        migrations.AddField(
            model_name='athlete',
            name='time_records',
            field=models.ManyToManyField(to='llegada.TimeRecord'),
        ),
    ]
