# Generated by Django 2.2.2 on 2019-06-17 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('llegada', '0002_auto_20180114_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='discipline',
            field=models.CharField(choices=[('SWI', 'Swimming'), ('TRA', 'Track'), ('TRI', 'Triathlon'), ('CYC', 'Cylclism'), ('MOT', 'Motorbike')], default='SWI', max_length=3),
        ),
        migrations.CreateModel(
            name='Result_Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_position', models.IntegerField()),
                ('category_position', models.IntegerField()),
                ('time_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llegada.TimeRecord')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
