# Generated by Django 2.0 on 2018-01-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llegada', '0003_auto_20171222_2007'),
    ]

    operations = [
    ]
