# Generated by Django 2.0 on 2018-01-02 18:30

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('llegada', '0004_auto_20180102_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerecord',
            name='id',
        ),
        migrations.AddField(
            model_name='timerecord',
            name='r_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='race',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
