# Generated by Django 2.0 on 2018-01-05 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llegada', '0004_auto_20180104_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='results',
        ),
        migrations.RemoveField(
            model_name='timerecord',
            name='result_race',
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='result_athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llegada.Registered_Athlete'),
        ),
    ]
