# Generated by Django 2.0 on 2018-01-02 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llegada', '0005_auto_20180102_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registered_Athlete',
            fields=[
                ('reg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llegada.Athlete')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llegada.Category')),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='available_categories',
            field=models.ManyToManyField(to='llegada.Category'),
        ),
        migrations.AddField(
            model_name='registered_athlete',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llegada.Race'),
        ),
    ]
