# Generated by Django 2.0 on 2018-01-02 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llegada', '0006_auto_20180102_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='reg_athletes',
        ),
    ]
